// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// BSPLeaveCenterCpp
Rcpp::NumericMatrix BSPLeaveCenterCpp(Rcpp::NumericMatrix data, SEXP numleaves, SEXP methodr);
RcppExport SEXP PAC_BSPLeaveCenterCpp(SEXP dataSEXP, SEXP numleavesSEXP, SEXP methodrSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< SEXP >::type numleaves(numleavesSEXP);
    Rcpp::traits::input_parameter< SEXP >::type methodr(methodrSEXP);
    __result = Rcpp::wrap(BSPLeaveCenterCpp(data, numleaves, methodr));
    return __result;
END_RCPP
}
